In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [83]:
X,y= make_regression(n_samples=100, n_features=5, n_informative=4, n_targets=1, noise=15, random_state=39)

# Train test split

In [84]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression

In [85]:
lr= LinearRegression()
lr.fit(X_train, y_train)
print("Coefficient: ", lr.coef_)
print("Intercept: ", lr.intercept_)
print("R2 Score for Normal Regression Line:", r2_score(y_test, lr.predict(X_test)))

Coefficient:  [-0.34097641 35.82824997 74.14652872 30.62076315  9.21293817]
Intercept:  1.4086083428436018
R2 Score for Normal Regression Line: 0.9394519268500224


# Applying Lasso Regression

In [86]:
alphas= [0.1, 1, 5, 10, 50]
for i in alphas:
    model= make_pipeline(StandardScaler(), Lasso(alpha=i))
    model.fit(X_train, y_train)
    print(f"R2 Score for alpha= {i}:", r2_score(y_test, model.predict(X_test)))
    lasso = model.named_steps['lasso']
    print("Lasso Coefficients:")
    print(lasso.coef_, "\n")

R2 Score for alpha= 0.1: 0.9394972632072895
Lasso Coefficients:
[-0.21933657 36.53440542 77.69571915 33.16539632  8.96053873] 

R2 Score for alpha= 1: 0.9405479279258563
Lasso Coefficients:
[-0.         35.46976334 76.51423066 32.30487003  8.11475141] 

R2 Score for alpha= 5: 0.9381102139421966
Lasso Coefficients:
[-0.         30.72693923 71.26486208 28.42331878  4.36650241] 

R2 Score for alpha= 10: 0.9152355009898221
Lasso Coefficients:
[-0.         24.76560764 64.75066505 23.5183277   0.        ] 

R2 Score for alpha= 50: 0.34026462572728444
Lasso Coefficients:
[ 0.          0.         21.43005984  0.          0.        ] 



##### What is named_steps? 



In [87]:
# Inside every pipeline, there is a dictionary called: model.named_steps. It stores each step by name. 
# It looks like:
# {
#    'standardscaler': StandardScaler(),
#    'lasso': Lasso(alpha=1)
# }

# lasso = model.named_steps['lasso']
# This means: "Go inside the pipeline, find the step named 'lasso', and give it to me."
# Now the variable lasso holds the actual trained Lasso model.